### ISSUE TITLE
Update poetry requirement for build system

### ISSUE THREAD

**Issue by elitherl** [ukaea/Indica#220]
Update poetry version to be PEP-517 compliant. Poetry suggested configuration:

```toml
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
